import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'いのししマップぎふ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`min-h-screen w-full antialiased`}>{children}</body>
    </html>
  );
}
