name: Build Check

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[meta]') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Build Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
            ${{ runner.os }}-
            refs/head/master
            
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
            
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
