name: Build Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[meta]') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Build Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
            ${{ runner.os }}-
            refs/head/master

      - name: Create Sentry Release
        shell: bash
        id: sentry_release
        run: |
          echo "::set-output name=env::${GITHUB_REF#refs/heads/}"
          echo "::set-output name=release::$(git show --format="%H" --no-patch)"
            
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ./
          build-args: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
            "NEXT_PUBLIC_SENTRY_ENVIRONMENT=${{ steps.sentry_release.outputs.env }}"
            "NEXT_PUBLIC_SENTRY_RELEASE=${{ steps.sentry_release.outputs.release }}"
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache